version: '3'
services:
  web:
    build:
      context: ..
      dockerfile: monitoring/Dockerfile
    image: h1cr.io/monitoring_web:${TAG_NAME-latest}
    environment:
      SMTP_URL: 'smtp://mailhog:1025'
      HYPERONE_USER: ${HYPERONE_USER}
      HYPERONE_PASSWORD: ${HYPERONE_PASSWORD}
      HYPERONE_PROJECT_MASTER: ${HYPERONE_PROJECT_MASTER}
      HYPERONE_PROJECT_SLAVE: ${HYPERONE_PROJECT_SLAVE}
      INFLUXDB_ADDRESS: '${INFLUXDB_HOST}'
      INFLUXDB_USERNAME: '${INFLUXDB_USERNAME}'
      INFLUXDB_PASSWORD: '${INFLUXDB_PASSWORD}'
      MONITORING_EMAILS: 'fail@example.com'
      MONITORING_SUCCESS_EMAILS: 'success@example.com'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    expose:
      - "1025/tcp"
